service/main/default/objects/FormResponseSending__mdt/FormResponseSending__mdt.object-meta.xml
<CustomObject>
    <description>Determine whether to automatically send a form to precise the case qualification or not according to the email address the customer reached.</description>
    <label>Form Response Sending</label>
    <pluralLabel>Form Response Sendings</pluralLabel>
</CustomObject>

service/main/default/objects/FormResponseSending__mdt/fields/EmailAddress__c.field-meta.xml
<CustomField>
    <fullName>EmailAddress__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Email address the client wrote to.</description>
    <label>Email Address</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

service/main/default/objects/FormResponseSending__mdt/fields/SendForm__c.field-meta.xml
<CustomField>
    <fullName>SendForm__c</fullName>
    <complianceGroup>RGPD</complianceGroup>
    <defaultValue>false</defaultValue>
    <description>Determines whether to send the form or not.</description>
    <label>Send Form</label>
    <type>Checkbox</type>
</CustomField>

service/main/default/classes/Service_FormResponseSendingUtilities.cls
/**
* @author Rémi Le Guin
* @date 10/10/2019
* @description Utility class for the Form Response Sending custom metadata whithin the Service package.
*/
public with sharing class Service_FormResponseSendingUtilities {

    public static final Map<String, Boolean> SENDFORMSBYEMAILADDRESS;

    static {
        SENDFORMSBYEMAILADDRESS = getSendFormsByEmailAddress();
    }

    /**
    * @description Get form sending decision according to email addresses.
    * @return A map of Booleans stating for sending by email address.
    */
    public static Map<String, Boolean> getSendFormsByEmailAddress() {
        Map<String,Boolean> sendFormsByEmailAddress = new Map<String, Boolean> ();
        for (FormResponseSending__mdt formResponseSending : [SELECT EmailAddress__c, SendForm__c
                                                             FROM FormResponseSending__mdt]) {
            SENDFORMSBYEMAILADDRESS.put(formResponseSending.EmailAddress__c, formResponseSending.SendForm__c);
        }
        return sendFormsByEmailAddress;
    }

}