service/main/default/objects/AutoResponseFormDisplay__mdt/AutoResponseFormDisplay__mdt.object-meta.xml
<CustomObject>
    <description>Determines which fields to display in a Service auto-response form.</description>
    <label>Auto-Response Form Display</label>
    <pluralLabel>Auto-Response Form Displays</pluralLabel>
</CustomObject>

service/main/default/objects/AutoResponseFormDisplay__mdt/fields/RequiredFields__c.field-meta.xml
<CustomField>
    <fullName>RequiredFields__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>Form&#39;s mandatory fields.</description>
    <inlineHelpText>Fields&#39; API names semi-colon-separated.</inlineHelpText>
    <label>Required Fields</label>
    <length>8192</length>
    <type>LongTextArea</type>
</CustomField>

service/main/default/objects/AutoResponseFormDisplay__mdt/fields/VisibleFields__c.field-meta.xml
<CustomField>
    <fullName>VisibleFields__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>Fields to display in the form.</description>
    <inlineHelpText>Fields&#39; API names semi-colon-separated.</inlineHelpText>
    <label>Visible Fields</label>
    <length>8192</length>
    <type>LongTextArea</type>
</CustomField>

service/main/default/objects/Case/fields/RequestSubtype__c.field-meta.xml
<CustomField>
    <fullName>RequestSubtype__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>Service request subtype.</description>
    <label>Request Subtype</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>RequestType__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Durée</fullName>
            </value>
            <value>
                <fullName>Kilométrage</fullName>
            </value>
            <value>
                <fullName>Durée et kilométrage</fullName>
            </value>
            <value>
                <fullName>Prestations</fullName>
            </value>
            <value>
                <fullName>Valeur de rachat</fullName>
            </value>
            <value>
                <fullName>Restitutions</fullName>
            </value>
            <value>
                <fullName>Adresses</fullName>
            </value>
            <value>
                <fullName>RIB</fullName>
            </value>
            <value>
                <fullName>Factures/Avoirs</fullName>
            </value>
            <value>
                <fullName>Contrat</fullName>
            </value>
            <value>
                <fullName>Echéancier</fullName>
            </value>
            <value>
                <fullName>Carte grise</fullName>
            </value>
            <value>
                <fullName>Je souscris à la prestation gestion carburant</fullName>
            </value>
            <value>
                <fullName>Je commande une ou plusieurs cartes</fullName>
            </value>
            <value>
                <fullName>Je résilie une ou plusieurs cartes</fullName>
            </value>
            <value>
                <fullName>Je déclare la perte, le vol ou l&#39;utilisation frauduleuse de ma carte</fullName>
            </value>
            <value>
                <fullName>Je n&#39;ai pas reçu mon certificat d&#39;immatriculation</fullName>
            </value>
            <value>
                <fullName>Je déclare un changement d&#39;adresse</fullName>
            </value>
            <value>
                <fullName>Je déclare un changement sur la situation de mon véhicule et/ou de mon entreprise</fullName>
            </value>
            <value>
                <fullName>J&#39;ai fait l&#39;objet d&#39;une usurpation de plaques</fullName>
            </value>
            <value>
                <fullName>Je souscris à la prestation conciergerie des immatriculations</fullName>
            </value>
            <value>
                <fullName>Je fais une demande sur la prestation conciergerie des immatriculations</fullName>
            </value>
            <value>
                <fullName>Je reçois une amende</fullName>
            </value>
            <value>
                <fullName>Je reçois une amende majorée</fullName>
            </value>
            <value>
                <fullName>Je reçois une amende étrangère</fullName>
            </value>
            <value>
                <fullName>Je souscris à la prestation gestion des amendes</fullName>
            </value>
            <value>
                <fullName>Je fais une demande sur la prestation gestion des amendes</fullName>
            </value>
            <value>
                <fullName>Je souscris à l&#39;assurance tous risques</fullName>
            </value>
            <value>
                <fullName>Je n&#39;ai pas reçu ma carte verte</fullName>
            </value>
            <value>
                <fullName>Je résilie l&#39;assurance tous risques</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

service/main/default/objects/Case/fields/RequestType__c.field-meta.xml
<CustomField>
    <fullName>RequestType__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>Service request type.</description>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Modifications contractuelles</fullName>
            </value>
            <value>
                <fullName>Valeur de rachat/Restitutions</fullName>
            </value>
            <value>
                <fullName>Modifications administratives</fullName>
            </value>
            <value>
                <fullName>Changement d’entité</fullName>
            </value>
            <value>
                <fullName>Duplicata</fullName>
            </value>
            <value>
                <fullName>Contestation de facture</fullName>
            </value>
            <value>
                <fullName>Frais de remise en état</fullName>
            </value>
            <value>
                <fullName>Loyer non arrêté</fullName>
            </value>
            <value>
                <fullName>Restitution</fullName>
            </value>
            <value>
                <fullName>Arrêt de l&#39;assurance</fullName>
            </value>
            <value>
                <fullName>Restitution anticipée</fullName>
            </value>
            <value>
                <fullName>Véhicule à enlever</fullName>
            </value>
            <value>
                <fullName>Expertise</fullName>
            </value>
            <value>
                <fullName>Remise en conformité du véhicule</fullName>
            </value>
            <value>
                <fullName>Désistement</fullName>
            </value>
            <value>
                <fullName>Détail de la facture</fullName>
            </value>
            <value>
                <fullName>Montant facturé</fullName>
            </value>
            <value>
                <fullName>Carburant</fullName>
            </value>
            <value>
                <fullName>Immatriculation des Véhicules</fullName>
            </value>
            <value>
                <fullName>Amendes</fullName>
            </value>
            <value>
                <fullName>Assurances</fullName>
            </value>
            <value>
                <fullName>Véhicule d&#39;attente</fullName>
            </value>
            <value>
                <fullName>Gestion de Parc</fullName>
            </value>
            <value>
                <fullName>Tarification</fullName>
            </value>
            <value>
                <fullName>Commande</fullName>
            </value>
            <value>
                <fullName>Avenant</fullName>
            </value>
            <value>
                <fullName>Transfert</fullName>
            </value>
            <value>
                <fullName>Sinistre</fullName>
            </value>
            <value>
                <fullName>Réclamation</fullName>
            </value>
            <value>
                <fullName>Autres</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

service/main/default/objects/Case/fields/VehicleRegistrationNumber__c.field-meta.xml
<CustomField>
    <fullName>VehicleRegistrationNumber__c</fullName>
    <complianceGroup>GDPR</complianceGroup>
    <description>Registration number for the vehicle related to the case.</description>
    <label>Vehicle Registration Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

service/main/default/objects/Case/recordTypes/Service_PublicDeals.recordType-meta.xml
<RecordType>
    <fullName>Service_PublicDeals</fullName>
    <active>true</active>
    <businessProcess>Service</businessProcess>
    <description>Record type for Service Public Deals cases.</description>
    <label>Service - Public Deals</label>
</RecordType>

service/main/default/classes/Service_AutoResponseFormController_Test.cls
/**
 * @author Rémi Le Guin
 * @date Creation 22/11/2019
 * @description Test class for the Auto-Response Form's Controller.
 */
@IsTest
private class Service_AutoResponseFormController_Test {

    @TestSetup
    private static void setup() {
        Id formProfileId = [SELECT Id FROM Profile WHERE Name = 'Form Profile' LIMIT 1][0].Id;

        User guestUser = (User)TDF.createSObject('User', new Map<String,Object> {
            'FirstName' => 'Guest',
            'LastName' => 'User',
            'Alias' => 'guest',
            'Email' => 'guestuser@form.fr',
            'Username' => 'guestuser@form.fr',
            'CommunityNickname' => 'guestuser',
            'ProfileId' => formProfileId,
			'BypassedObjectRestrictions__c' => 'Case (Edit)'
        });
        Id autoResponseFormPermissionId = [SELECT Id FROM PermissionSet WHERE Name = 'Service_AutoResponseForm' LIMIT 1][0].Id;
        insert new PermissionSetAssignment (PermissionSetId = autoResponseFormPermissionId, AssigneeId = guestUser.Id);
        Id coreUserPermissionId = [SELECT Id FROM PermissionSet WHERE Name = 'Core_User' LIMIT 1][0].Id;
        insert new PermissionSetAssignment (PermissionSetId = coreUserPermissionId, AssigneeId = guestUser.Id);

        User unauthorizedUser = (User)TDF.createSObject('User', new Map<String,Object> {
            'FirstName' => 'Unauthorized',
            'LastName' => 'User',
            'Alias' => 'unauth',
            'Email' => 'unauthorizeduser@form.fr',
            'Username' => 'unauthorizeduser@form.fr',
            'CommunityNickname' => 'unauthorizeduser',
            'ProfileId' => formProfileId
        });

		System.runAs(guestUser) {
			Case cs = (Case)TDF.createSObject('Case', new Map<String,Object> {
				'RecordTypeId' => Service_CaseUtilities.RECORDTYPEID_PUBLICDEALS,
				'Origin' => 'Email',
				'Priority' => 'Low',
				'OwnerId' => Service_CaseUtilities.SERVICEQUEUEIDSBYDEVELOPERNAME.get('Service_PublicDeals'),
				'SuppliedEmail' => 'test@email.com'
			});
		}
    }

	/**
	 * @description Test the getAutoResponseFormDisplayByFloor method when user has access to the AutoResponseFormDisplay__mdt custom metadata.
	 */
	@IsTest
	private static void getRecordTypeNameById_TestNoRT() {
        User guestUser = [SELECT Id FROM User WHERE Username = 'guestuser@form.fr' LIMIT 1];

		Id recordTypeDeveloperName;
		Test.startTest();
		System.runAs(guestUser) {
			recordTypeDeveloperName = Service_AutoResponseFormController.getRecordTypeNameById('000000000000000000');
		}
		Test.stopTest();

		System.assertEquals(null, recordTypeDeveloperName);
	}

	/**
	 * @description Test the getAutoResponseFormDisplayByFloor method when user has access to the AutoResponseFormDisplay__mdt custom metadata.
	 */
	@IsTest
	private static void getAutoResponseFormDisplayByFloor_TestSuccess() {
        User guestUser = [SELECT Id FROM User WHERE Username = 'guestuser@form.fr' LIMIT 1];

		AutoResponseFormDisplay__mdt display;
		Test.startTest();
		System.runAs(guestUser) {
			display = Service_AutoResponseFormController.getAutoResponseFormDisplayByFloor('TestFloor');
		}
		Test.stopTest();

		System.assertEquals('TestVisibleField', display.VisibleFields__c, 'Wrong or no metadata retrieved');
		System.assertEquals('TestRequiredField', display.RequiredFields__c, 'Wrong or no metadata retrieved');
	}

	/**
	 * @description Test the getAutoResponseFormDisplayByFloor method when user has not access to the AutoResponseFormDisplay__mdt custom metadata.
	 */
    // The test method is deactivated for now because scratch orgs automatically created do not enforce CRUD on custom metadata.
    // On February 2020, direct access to a custom metadata will have to be granted.
    /*
	@IsTest
	private static void getAutoResponseFormDisplayByFloor_TestError() {
        User guestUser = [SELECT Id FROM User WHERE Username = 'unauthorizeduser@form.fr' LIMIT 1];

		AutoResponseFormDisplay__mdt display;
		Test.startTest();
		System.runAs(guestUser) {
			display = Service_AutoResponseFormController.getAutoResponseFormDisplayByFloor('TestFloor');
		}
		Test.stopTest();

		System.assertEquals(null, display, 'Metadata retrieved while it should not');
	}
    */
	/**
	 * @description Test the updateCase method when success.
	 */
	@IsTest
	private static void updateCase_TestSuccess() {
		User guestUser = [SELECT Id FROM User WHERE Username = 'guestuser@form.fr' LIMIT 1];
		Case cs = [SELECT Id FROM Case LIMIT 1];
		Map<String, Object> fields = new Map<String, Object> ();
		fields.put('RequestType__c', 'Duplicata');
		fields.put('RequestSubtype__c', 'Factures/Avoirs');
		fields.put('VehicleRegistrationNumber__c', '123-AB-00');

		String returnMessage;
		Test.startTest();
		System.runAs(guestUser) {
			returnMessage = Service_AutoResponseFormController.updateCase(cs.Id, fields);
		}
		Test.stopTest();

		System.assertEquals('Success', returnMessage, 'The update failed.');
		cs = [SELECT RequestType__c, RequestSubtype__c, VehicleRegistrationNumber__c FROM Case LIMIT 1];
		System.assertEquals('Duplicata', cs.RequestType__c, 'Wrong value set for Case\'s request type.');
		System.assertEquals('Factures/Avoirs', cs.RequestSubtype__c, 'Wrong value set for Case\'s sub request type.');
		System.assertEquals('123-AB-00', cs.VehicleRegistrationNumber__c, 'Wrong value set for Case\'s vehicle registration number.');
	}
    
}